"""refix datetime

Revision ID: 4853c1c90588
Revises: 103a75b38300
Create Date: 2025-08-01 20:43:11.047031

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4853c1c90588"
down_revision: Union[str, Sequence[str], None] = "103a75b38300"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "exchanges", sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True)
    )
    op.add_column(
        "exchanges", sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True)
    )
    op.add_column(
        "reviews", sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True)
    )
    op.add_column(
        "skills", sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True)
    )
    op.add_column(
        "skills", sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True)
    )
    op.add_column(
        "users", sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True)
    )
    op.add_column(
        "users", sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "updated_at")
    op.drop_column("users", "created_at")
    op.drop_column("skills", "updated_at")
    op.drop_column("skills", "created_at")
    op.drop_column("reviews", "created_at")
    op.drop_column("exchanges", "updated_at")
    op.drop_column("exchanges", "created_at")
    # ### end Alembic commands ###
